xp: update bsp
commit e065b00
Author: WanWizard <wanwizard@openpli.org>
Date:   Sat Aug 9 14:55:14 2025 +0100

    linux-xp_4.10.12: Remove PKG:{PN} which rename to existing package

    ERROR: linux-xp-4.10.12-r1.0 do_package: package "kernel-base" is renamed to "kernel-base" using PKG:kernel-base, but package name already exists

    https://git.openembedded.org/openembedded-core/commit/?id=f6cb63d3a871c4eef52d981131a56bf41aa1dcdf