gittag.bbclass: pipes module has been removed with Python 3.13
Replace with shlex module.
Fix build on host with Python 3.13.

bb.data_smart.ExpansionError: Failure expanding variable GITPKGVTAG, expression was
${@get_git_pkgv(d, True)} which triggered exception ModuleNotFoundError: No module named 'pipes'